# Generated by Django 5.0.1 on 2024-01-14 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Номер самолета')),
                ('travel_time', models.PositiveIntegerField(verbose_name='Время в пути')),
                ('fromCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city_set', to='main.city', verbose_name='Из какого города')),
                ('toCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city_set', to='main.city', verbose_name='В какой город')),
            ],
            options={
                'verbose_name': 'Самолет',
                'verbose_name_plural': 'Самолеты',
                'ordering': ('travel_time',),
            },
        ),
    ]
